language: node_js
node_js: '8'
stages:
  - name: check contract format
  - name: check token format

jobs:
  fast_finish: true
  include:
    - stage: check contract format
      script:
        - |
          contractErrors=$(node checkContract.js);
          if [[ $contractErrors != 0 ]]; then
            echo "Formatting errors! Please check your object keys spellings, commas and or other things that might invalidate your JSON and try again";
            exit 1;
          else
            echo "No errors";
            exit 0;
          fi
    - stage: check token format
      script:
        - |
          tokenErrors=$(node checkToken.js);
          if [[ $tokenErrors != 0 ]]; then
            echo "Formatting errors! Please check your object keys spellings, commas and or other things that might invalidate your JSON and try again";
            exit 1;
          else
            echo "No errors";
            exit 0;
          fi
