language: node_js
node_js: '8'
stages:
  - name: check contract format
  - name: check token format

jobs:
  fast_finish: true
  include:
    - stage: check contract format
      script:
        - |
          node checkContract.js;
    - stage: check token format
      script:
        - |
          node checkToken.js;
