language: node_js
node_js: '8'
stages:
  - name: check formatting issues

jobs:
  fast_finish: true
  include:
    - stage: check formatting issues
      script:
        - |
          npm run compile
